name: beautifulyeti.auth

services:
  by-auth:
    image: by-auth
    ports:
      - "8443:8443"
    environment:
      ENCRYPTION_KEY: ${ENCRYPTION_KEY}
      OIDC_PROVIDER_URL: ${OIDC_PROVIDER_URL}
      OIDC_PROVIDER_LOGOUT_URL: ${OIDC_PROVIDER_LOGOUT_URL}
      OIDC_REDIRECT_URL: ${OIDC_REDIRECT_URL}
      OIDC_CLIENT_ID: ${OIDC_CLIENT_ID}
      OIDC_CLIENT_SECRET: ${OIDC_CLIENT_SECRET}
      REDIS_ADDRESS: ${REDIS_ADDRESS}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      SESSION_COOKIE_NAME: ${SESSION_COOKIE_NAME}
      SHARED_API_KEYS: ${SHARED_API_KEYS}
      USE_DEV_CERTS: ${USE_DEV_CERTS}
      SERVER_ADDRESS: ${SERVER_ADDRESS}
    depends_on:
      - redis
    healthcheck:
      test: [ "CMD", "./server", "healthcheck", "-host", "localhost", "-port", "8443", "-insecure=true" ]
      interval: 30s
      timeout: 5s
      retries: 3

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    restart: unless-stopped